### ISSUE TITLE
Detects iPad as isMobile()

### ISSUE THREAD

**Issue by Thunderofnl** [suncat2000/MobileDetectBundle#103]
I'm not sure if this is correct behavior, but it seems when I use `isMobile()` it will also return true if it's on an iPad or other tablet. If this is normal behavior, how would I check for mobile phones only?

**Comment by xabbuh** [comment]
`isMobile() && !isTablet()` (pseudo code) should give you the expected result

**Comment by Thunderofnl** [comment]
Thanks!
