### ISSUE TITLE
Not configurable server status code on switch param redirect

### ISSUE THREAD

**Issue by todpetkov** [suncat2000/MobileDetectBundle#107]
When redirecting by switch parameter the server status code is now hardcoded to 302 and doesn't use config options.
Here is the place in the source: https://github.com/suncat2000/MobileDetectBundle/blob/master/Helper/DeviceView.php, line 225 (inside method getRedirectResponseBySwitchParam())

**Comment by suncat2000** [comment]
@todpetkov yes(((
I am fix it when I have free time.

**Comment by suncat2000** [comment]
@todpetkov fixed by @orions
