### ISSUE TITLE
SF 3.2.13 compatibility ?

### ISSUE THREAD

**Issue by xorgxx** [suncat2000/MobileDetectBundle#118]
Hi i just try to install on SF 3.2.13 and i get 
```
  Problem 1
    - Installation request for suncat/mobile-detect-bundle v1.0.6 -> satisfiable by suncat/mobile-detect-bundle[v1.0.6].
    - Conclusion: remove symfony/symfony v3.2.13
    - Conclusion: don't install symfony/symfony v3.2.13
```
it mean that i have to update SF to 3.3 ?
Thank.

**Comment by xabbuh** [comment]
MobileDetectBundle 1.0.5 would work with Symfony 3.2.

But since [Symfony 3.2 does not receive bug fixes anymore](http://symfony.com/roadmap?version=3.2#checker) upgrading to 3.3 is indeed a good idea nonetheless.

**Comment by xorgxx** [comment]
ok thank, i will try to update to 3.3.
