### ISSUE TITLE
Is this bundle still maintained?

### ISSUE THREAD

**Issue by bocharsky-bw** [suncat2000/MobileDetectBundle#124]
We have some tickets like #122 which just should be merged

**Comment by bocharsky-bw** [comment]
Any alternative maintainer for this bundle to push things forward a little bit?

ping @suncat2000

**Comment by suncat2000** [comment]
@bocharsky-bw fixed [v1.1.0](https://github.com/suncat2000/MobileDetectBundle/tree/v1.1.0)

**Comment by bocharsky-bw** [comment]
Thanks!
