### ISSUE TITLE
Symfony 4: The profiler template "MobileDetectBundle:Collector:device.html.twig" for data collector "device.collector" does not exist.

### ISSUE THREAD

**Issue by dhananjay88** [suncat2000/MobileDetectBundle#125]
MobileDetect bundle 1.1.0 was working fine with Symfony 3.4 but after upgrading to Symfony 4, symfony toolbar stopped working because of the below error
The profiler template "MobileDetectBundle:Collector:device.html.twig" for data collector "device.collector" does not exist.

Does this version (1.1.0) support Symfony 4?

**Comment by xabbuh** [comment]
see #123

**Comment by ephp** [comment]
I've the same problem too.  I had to comment on the listener.xml reading

**Comment by abarke** [comment]
I have the same issue on PHP 7.1 and MobileDetectBundle 1.1.0

**Comment by Crikripex** [comment]
Hi, I'm having the exact same error on the same configuration, did anyone find a way to fix this?

**Comment by abarke** [comment]
In still getting this issue in the web debug toolbar. Did someone test PHP 7 with Symfony 4?

suncat/mobile-detect-bundle: "1.1.0"

Please fix this as I would like to use the debug toolbar and mobile detect in Symfony.

**Comment by xabbuh** [comment]
There hasn't been any new release since #127 was merged.

**Comment by suncat2000** [comment]
@abarke I add release [v1.1.1](https://github.com/suncat2000/MobileDetectBundle/tree/v1.1.1)

**Comment by xabbuh** [comment]
@suncat2000 I think you can close this issue then too. :)
