### ISSUE TITLE
How configure tablets to be desktop view?

### ISSUE THREAD

**Issue by Don87** [suncat2000/MobileDetectBundle#66]
This is a lovely bundle. Does anyone know how I can configure all tablets to show the desktop view by default? I am not even interested in switching them to mobile. Thanks.

**Comment by Don87** [comment]
This is my config.yml

mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~
    service:
        mobile_detector: mobile_detect.mobile_detector.default
    device_view_class: SunCat\MobileDetectBundle\Helper\DeviceView
    request_listener_class: SunCat\MobileDetectBundle\EventListener\RequestListener
    extension_class: SunCat\MobileDetectBundle\Twig\Extension\MobileDetectExtension

**Comment by netmikey** [comment]
It looks like you don't have any redirects configured yet. Is your application redirecting yet?

btw: (at least) the last 5 lines of your configuration are all default values, you can omit them.
