### ISSUE TITLE
Optional cookie

### ISSUE THREAD

**Issue by romaricdrigon** [suncat2000/MobileDetectBundle#68]
Hi,

Right now the `RequestListener` sets a cookie with the `device_view`.
It would be great to be able to disable that cookie behavior by setting a parameter in configuration.

A typical use case would be for tests/`dev` environment: at the moment we can't use Chrome dev tools properly.

**Comment by netmikey** [comment]
Hi @romaricdrigon,

As far as I remember, the cookie is required to remember the desired target device view, whether it had been detected or overridden via the `device_view` GET parameter. If it wasn't set, device detection would take place on each and every http request and overriding the device detection wouldn't be possible anymore.

What is the problem with cookies and Chrome dev tools anyway?

**Comment by romaricdrigon** [comment]
Hi,

Exactly. But having the detection to be run on every request is totally acceptable in dev environment, actually that would makes sense since the whole dev mode is made for this (Symfony2 checks config, routes and so on on every request too...).

With Chrome dev tools you can emulate mobile devices. But then they the whole cookie-setting thing fails. That also apply to pretty much in mobile-testing tool too.

**Comment by suncat2000** [comment]
fixed in [v1.0.0](https://github.com/suncat2000/MobileDetectBundle/tree/v1.0.0)
