### ISSUE TITLE
Container::isScopeActive method is deprecated since version 2.8

### ISSUE THREAD

**Issue by ickbinhier** [suncat2000/MobileDetectBundle#82]
The Symfony\Component\DependencyInjection\Container::isScopeActive method is deprecated since version 2.8 and will be removed in 3.0

in Line 65
https://github.com/suncat2000/MobileDetectBundle/blob/master/Helper/DeviceView.php#L65

**Comment by tubssp** [comment]
a pull request is existent

https://github.com/suncat2000/MobileDetectBundle/pull/80

**Comment by suncat2000** [comment]
fixed in [v1.0.0](https://github.com/suncat2000/MobileDetectBundle/tree/v1.0.0)
