### ISSUE TITLE
Symfony 3.1

### ISSUE THREAD

**Issue by tsantos84** [suncat2000/MobileDetectBundle#83]
I need to use MobileDetectBundle with the must recent version of Symfony (3.1). There is some restriction upgrade your composer?

**Comment by xabbuh** [comment]
Do you really want to use Symfony 3.1 which is still in development? For Symfony 3.0 support, you can take a look at #80.

**Comment by tsantos84** [comment]
Hi @xabbuh, thanks for your replay. I agree with you and I'll use the SF 3.0 version. But I'm still having problems with the composer. I'll close this issue and reply on #80.
