### ISSUE TITLE
Is MobileDetect compatible with Symfony 3.0 ?

### ISSUE THREAD

**Issue by eved42** [suncat2000/MobileDetectBundle#87]
Hi everyone,

I tried to install your bundle with composer on my symfony 3.0 project but the installation failed.
Usually, does it work with symfony 3 ?

Thanks.

**Comment by xabbuh** [comment]
Not, it's not compatible yet (see #80).

**Comment by eved42** [comment]
Thanks for your answer.

Meanwhile, I found a lighter version which works with Symfony 3.0 : 
https://github.com/bes89/mobiledetect-twig-extension

Example : check device type with twig : 
`{% if is_mobile() %} ... {% endif %}`
`{% if is_tablet() %} ... {% endif %}`

**Comment by suncat2000** [comment]
@eved42 add sf 3.0 support in [v1.0.2](https://github.com/suncat2000/MobileDetectBundle/tree/v1.0.2)
