### ISSUE TITLE
Compatibilité Symfony 3

### ISSUE THREAD

**Issue by relax7611** [suncat2000/MobileDetectBundle#88]
Bonjour,
Le bundle n'est actuellement pas compatible avec Symfony 3, auriez-vous une date de mise à jour pour rendre compatible le bundle en question ?
 Problem 1
    - Conclusion: remove symfony/symfony v3.0.2
    - Conclusion: don't install symfony/symfony v3.0.2
    - Conclusion: don't install symfony/symfony v3.0.1
Merci de votre compréhension 
Cordialement

**Comment by xabbuh** [comment]
I don't speak French but it seems you are looking for Symfony 3 support in this bundle. The code is not ready yet afaics (have a look at #80).

**Comment by relax7611** [comment]
Hello,
Thank you for your reply , the code for symfony 3 will be ready when?
Thank you.

**Comment by xsuntel** [comment]
Hello,

 I look forward to hearing from you. because I have same issue on Symfony 3.0.3

Best Regards.

**Comment by suncat2000** [comment]
fixed in [v1.0.0](https://github.com/suncat2000/MobileDetectBundle/tree/v1.0.0)
