### ISSUE TITLE
MobileDetectBundle doesn't work with BeSimple\I18nRoutingBundle

### ISSUE THREAD

**Issue by marcu87** [suncat2000/MobileDetectBundle#92]
Hello, I'm getting this error trying to use this bundle. 

_Catchable Fatal Error: Argument 3 passed to SunCat\MobileDetectBundle\EventListener\RequestResponseListener::__construct() must be an instance of Symfony\Bundle\FrameworkBundle\Routing\Router, instance of BeSimple\I18nRoutingBundle\Routing\Router given, called in /var/www/c2is/oceania_hotels2/app/cache/dev/appDevDebugProjectContainer.php on line 5140 and defined_

The problem is that I'm not using the classic symfony routing, but **BeSimple\I18nRoutingBundle**.

And in the construct(), there is a line: 

```
    public function __construct(
        MobileDetector $mobileDetector,
        DeviceView $deviceView,
        Router $router,
        array $redirectConf,
        $fullPath = true
    )
```

The expected **Router** is Symfony\Component\Routing\Route...

I'm not even interested in use all the routing functionalities of the module, just a simple:

```
$mobileDetector = $this->get('mobile_detect.mobile_detector');
$mobileDetector->isMobile();
```

Is this a bug or how can I avoid this error? 
Thanks for the help,

**Comment by suncat2000** [comment]
Hello @marcu87, it is fixed in this PR https://github.com/suncat2000/MobileDetectBundle/pull/90.
I push new version [v1.0.3](https://github.com/suncat2000/MobileDetectBundle/tree/v1.0.3) with this fix.
